/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RandomLolOldRouteImport } from './routes/random-lol-old'
import { Route as RandomLolRouteImport } from './routes/random-lol'
import { Route as RandomLaneRouteImport } from './routes/random-lane'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HuongDanRouteImport } from './routes/huong-dan'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CustomGameRandomRouteImport } from './routes/custom-game-random'
import { Route as CmvnRouteImport } from './routes/cmvn'
import { Route as ChiaTeamLienMinhRouteImport } from './routes/chia-team-lien-minh'
import { Route as AramRandomRouteImport } from './routes/aram-random'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleRandomLolRouteImport } from './routes/$locale/random-lol'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomLolOldRoute = RandomLolOldRouteImport.update({
  id: '/random-lol-old',
  path: '/random-lol-old',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomLolRoute = RandomLolRouteImport.update({
  id: '/random-lol',
  path: '/random-lol',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomLaneRoute = RandomLaneRouteImport.update({
  id: '/random-lane',
  path: '/random-lane',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanRoute = HuongDanRouteImport.update({
  id: '/huong-dan',
  path: '/huong-dan',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomGameRandomRoute = CustomGameRandomRouteImport.update({
  id: '/custom-game-random',
  path: '/custom-game-random',
  getParentRoute: () => rootRouteImport,
} as any)
const CmvnRoute = CmvnRouteImport.update({
  id: '/cmvn',
  path: '/cmvn',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiaTeamLienMinhRoute = ChiaTeamLienMinhRouteImport.update({
  id: '/chia-team-lien-minh',
  path: '/chia-team-lien-minh',
  getParentRoute: () => rootRouteImport,
} as any)
const AramRandomRoute = AramRandomRouteImport.update({
  id: '/aram-random',
  path: '/aram-random',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRandomLolRoute = LocaleRandomLolRouteImport.update({
  id: '/random-lol',
  path: '/random-lol',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/aram-random': typeof AramRandomRoute
  '/chia-team-lien-minh': typeof ChiaTeamLienMinhRoute
  '/cmvn': typeof CmvnRoute
  '/custom-game-random': typeof CustomGameRandomRoute
  '/faq': typeof FaqRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan': typeof HuongDanRoute
  '/login': typeof LoginRoute
  '/random-lane': typeof RandomLaneRoute
  '/random-lol': typeof RandomLolRoute
  '/random-lol-old': typeof RandomLolOldRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/random-lol': typeof LocaleRandomLolRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aram-random': typeof AramRandomRoute
  '/chia-team-lien-minh': typeof ChiaTeamLienMinhRoute
  '/cmvn': typeof CmvnRoute
  '/custom-game-random': typeof CustomGameRandomRoute
  '/faq': typeof FaqRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan': typeof HuongDanRoute
  '/login': typeof LoginRoute
  '/random-lane': typeof RandomLaneRoute
  '/random-lol': typeof RandomLolRoute
  '/random-lol-old': typeof RandomLolOldRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/random-lol': typeof LocaleRandomLolRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/aram-random': typeof AramRandomRoute
  '/chia-team-lien-minh': typeof ChiaTeamLienMinhRoute
  '/cmvn': typeof CmvnRoute
  '/custom-game-random': typeof CustomGameRandomRoute
  '/faq': typeof FaqRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan': typeof HuongDanRoute
  '/login': typeof LoginRoute
  '/random-lane': typeof RandomLaneRoute
  '/random-lol': typeof RandomLolRoute
  '/random-lol-old': typeof RandomLolOldRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/random-lol': typeof LocaleRandomLolRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/aram-random'
    | '/chia-team-lien-minh'
    | '/cmvn'
    | '/custom-game-random'
    | '/faq'
    | '/gioi-thieu'
    | '/huong-dan'
    | '/login'
    | '/random-lane'
    | '/random-lol'
    | '/random-lol-old'
    | '/sitemap.xml'
    | '/$locale/login'
    | '/$locale/random-lol'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aram-random'
    | '/chia-team-lien-minh'
    | '/cmvn'
    | '/custom-game-random'
    | '/faq'
    | '/gioi-thieu'
    | '/huong-dan'
    | '/login'
    | '/random-lane'
    | '/random-lol'
    | '/random-lol-old'
    | '/sitemap.xml'
    | '/$locale/login'
    | '/$locale/random-lol'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/aram-random'
    | '/chia-team-lien-minh'
    | '/cmvn'
    | '/custom-game-random'
    | '/faq'
    | '/gioi-thieu'
    | '/huong-dan'
    | '/login'
    | '/random-lane'
    | '/random-lol'
    | '/random-lol-old'
    | '/sitemap.xml'
    | '/$locale/login'
    | '/$locale/random-lol'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AramRandomRoute: typeof AramRandomRoute
  ChiaTeamLienMinhRoute: typeof ChiaTeamLienMinhRoute
  CmvnRoute: typeof CmvnRoute
  CustomGameRandomRoute: typeof CustomGameRandomRoute
  FaqRoute: typeof FaqRoute
  GioiThieuRoute: typeof GioiThieuRoute
  HuongDanRoute: typeof HuongDanRoute
  LoginRoute: typeof LoginRoute
  RandomLaneRoute: typeof RandomLaneRoute
  RandomLolRoute: typeof RandomLolRoute
  RandomLolOldRoute: typeof RandomLolOldRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-lol-old': {
      id: '/random-lol-old'
      path: '/random-lol-old'
      fullPath: '/random-lol-old'
      preLoaderRoute: typeof RandomLolOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-lol': {
      id: '/random-lol'
      path: '/random-lol'
      fullPath: '/random-lol'
      preLoaderRoute: typeof RandomLolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-lane': {
      id: '/random-lane'
      path: '/random-lane'
      fullPath: '/random-lane'
      preLoaderRoute: typeof RandomLaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan': {
      id: '/huong-dan'
      path: '/huong-dan'
      fullPath: '/huong-dan'
      preLoaderRoute: typeof HuongDanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-game-random': {
      id: '/custom-game-random'
      path: '/custom-game-random'
      fullPath: '/custom-game-random'
      preLoaderRoute: typeof CustomGameRandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cmvn': {
      id: '/cmvn'
      path: '/cmvn'
      fullPath: '/cmvn'
      preLoaderRoute: typeof CmvnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chia-team-lien-minh': {
      id: '/chia-team-lien-minh'
      path: '/chia-team-lien-minh'
      fullPath: '/chia-team-lien-minh'
      preLoaderRoute: typeof ChiaTeamLienMinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aram-random': {
      id: '/aram-random'
      path: '/aram-random'
      fullPath: '/aram-random'
      preLoaderRoute: typeof AramRandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/random-lol': {
      id: '/$locale/random-lol'
      path: '/random-lol'
      fullPath: '/$locale/random-lol'
      preLoaderRoute: typeof LocaleRandomLolRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleRandomLolRoute: typeof LocaleRandomLolRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleRandomLolRoute: LocaleRandomLolRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AramRandomRoute: AramRandomRoute,
  ChiaTeamLienMinhRoute: ChiaTeamLienMinhRoute,
  CmvnRoute: CmvnRoute,
  CustomGameRandomRoute: CustomGameRandomRoute,
  FaqRoute: FaqRoute,
  GioiThieuRoute: GioiThieuRoute,
  HuongDanRoute: HuongDanRoute,
  LoginRoute: LoginRoute,
  RandomLaneRoute: RandomLaneRoute,
  RandomLolRoute: RandomLolRoute,
  RandomLolOldRoute: RandomLolOldRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
