/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RandomLaneRouteImport } from './routes/random-lane'
import { Route as HuongDanRouteImport } from './routes/huong-dan'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CustomGameRandomRouteImport } from './routes/custom-game-random'
import { Route as CmvnRouteImport } from './routes/cmvn'
import { Route as ChiaTeamLienMinhRouteImport } from './routes/chia-team-lien-minh'
import { Route as AramRandomRouteImport } from './routes/aram-random'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V2RandomRouteImport } from './routes/v2.random'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomLaneRoute = RandomLaneRouteImport.update({
  id: '/random-lane',
  path: '/random-lane',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanRoute = HuongDanRouteImport.update({
  id: '/huong-dan',
  path: '/huong-dan',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomGameRandomRoute = CustomGameRandomRouteImport.update({
  id: '/custom-game-random',
  path: '/custom-game-random',
  getParentRoute: () => rootRouteImport,
} as any)
const CmvnRoute = CmvnRouteImport.update({
  id: '/cmvn',
  path: '/cmvn',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiaTeamLienMinhRoute = ChiaTeamLienMinhRouteImport.update({
  id: '/chia-team-lien-minh',
  path: '/chia-team-lien-minh',
  getParentRoute: () => rootRouteImport,
} as any)
const AramRandomRoute = AramRandomRouteImport.update({
  id: '/aram-random',
  path: '/aram-random',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2RandomRoute = V2RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => V2Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aram-random': typeof AramRandomRoute
  '/chia-team-lien-minh': typeof ChiaTeamLienMinhRoute
  '/cmvn': typeof CmvnRoute
  '/custom-game-random': typeof CustomGameRandomRoute
  '/faq': typeof FaqRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan': typeof HuongDanRoute
  '/random-lane': typeof RandomLaneRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/v2': typeof V2RouteWithChildren
  '/v2/random': typeof V2RandomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aram-random': typeof AramRandomRoute
  '/chia-team-lien-minh': typeof ChiaTeamLienMinhRoute
  '/cmvn': typeof CmvnRoute
  '/custom-game-random': typeof CustomGameRandomRoute
  '/faq': typeof FaqRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan': typeof HuongDanRoute
  '/random-lane': typeof RandomLaneRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/v2': typeof V2RouteWithChildren
  '/v2/random': typeof V2RandomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aram-random': typeof AramRandomRoute
  '/chia-team-lien-minh': typeof ChiaTeamLienMinhRoute
  '/cmvn': typeof CmvnRoute
  '/custom-game-random': typeof CustomGameRandomRoute
  '/faq': typeof FaqRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan': typeof HuongDanRoute
  '/random-lane': typeof RandomLaneRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/v2': typeof V2RouteWithChildren
  '/v2/random': typeof V2RandomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aram-random'
    | '/chia-team-lien-minh'
    | '/cmvn'
    | '/custom-game-random'
    | '/faq'
    | '/gioi-thieu'
    | '/huong-dan'
    | '/random-lane'
    | '/sitemap.xml'
    | '/v2'
    | '/v2/random'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aram-random'
    | '/chia-team-lien-minh'
    | '/cmvn'
    | '/custom-game-random'
    | '/faq'
    | '/gioi-thieu'
    | '/huong-dan'
    | '/random-lane'
    | '/sitemap.xml'
    | '/v2'
    | '/v2/random'
  id:
    | '__root__'
    | '/'
    | '/aram-random'
    | '/chia-team-lien-minh'
    | '/cmvn'
    | '/custom-game-random'
    | '/faq'
    | '/gioi-thieu'
    | '/huong-dan'
    | '/random-lane'
    | '/sitemap.xml'
    | '/v2'
    | '/v2/random'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AramRandomRoute: typeof AramRandomRoute
  ChiaTeamLienMinhRoute: typeof ChiaTeamLienMinhRoute
  CmvnRoute: typeof CmvnRoute
  CustomGameRandomRoute: typeof CustomGameRandomRoute
  FaqRoute: typeof FaqRoute
  GioiThieuRoute: typeof GioiThieuRoute
  HuongDanRoute: typeof HuongDanRoute
  RandomLaneRoute: typeof RandomLaneRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  V2Route: typeof V2RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-lane': {
      id: '/random-lane'
      path: '/random-lane'
      fullPath: '/random-lane'
      preLoaderRoute: typeof RandomLaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan': {
      id: '/huong-dan'
      path: '/huong-dan'
      fullPath: '/huong-dan'
      preLoaderRoute: typeof HuongDanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-game-random': {
      id: '/custom-game-random'
      path: '/custom-game-random'
      fullPath: '/custom-game-random'
      preLoaderRoute: typeof CustomGameRandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cmvn': {
      id: '/cmvn'
      path: '/cmvn'
      fullPath: '/cmvn'
      preLoaderRoute: typeof CmvnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chia-team-lien-minh': {
      id: '/chia-team-lien-minh'
      path: '/chia-team-lien-minh'
      fullPath: '/chia-team-lien-minh'
      preLoaderRoute: typeof ChiaTeamLienMinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aram-random': {
      id: '/aram-random'
      path: '/aram-random'
      fullPath: '/aram-random'
      preLoaderRoute: typeof AramRandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/random': {
      id: '/v2/random'
      path: '/random'
      fullPath: '/v2/random'
      preLoaderRoute: typeof V2RandomRouteImport
      parentRoute: typeof V2Route
    }
  }
}

interface V2RouteChildren {
  V2RandomRoute: typeof V2RandomRoute
}

const V2RouteChildren: V2RouteChildren = {
  V2RandomRoute: V2RandomRoute,
}

const V2RouteWithChildren = V2Route._addFileChildren(V2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AramRandomRoute: AramRandomRoute,
  ChiaTeamLienMinhRoute: ChiaTeamLienMinhRoute,
  CmvnRoute: CmvnRoute,
  CustomGameRandomRoute: CustomGameRandomRoute,
  FaqRoute: FaqRoute,
  GioiThieuRoute: GioiThieuRoute,
  HuongDanRoute: HuongDanRoute,
  RandomLaneRoute: RandomLaneRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  V2Route: V2RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
